New questions about permanent data owner
rdmorganiser/rdmo-catalog pull request #111
Opened 2021-11-16 10:51 UTC by ClaraRosalie

New questions and attributes added as suggested in #110.

An italian and french translation cannot be provided.

2021-11-16 11:11 UTC, jmfrenzel approved these changes
This looks good. 

Note I'm involved in this contribution from UA Ruhr (see linked issue #110). 

@torsten-rathmann @Zack-83 what do you think?

2021-11-17 07:27 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +	  <dc:comment>Refers to the permanent project owner see #110</dc:comment>
```suggestion
	  <dc:comment>Refers to the permanent project owner: see #110https://github.com/rdmorganiser/rdmo-catalog/issues/110</dc:comment>
```

2021-11-17 07:29 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +	  <key>responsible_person_name</key>
The key should be equal to the last part of the attribute URI. So please choose, either only `name` (shorter) or `responsible_person_name` (nonambiguous).

2021-11-17 07:30 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +	  <dc:comment>Refers to the permanent project owner see #110</dc:comment>
```suggestion
	  <dc:comment>Refers to the permanent project owner: see #110https://github.com/rdmorganiser/rdmo-catalog/issues/110</dc:comment>
```

2021-11-17 07:30 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +	  <dc:comment>Refers to the permanent project owner see #110</dc:comment>
```suggestion
	  <dc:comment>Refers to the permanent project owner: see https://github.com/rdmorganiser/rdmo-catalog/issues/110</dc:comment>
```

2021-11-17 07:31 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +	  <key>responsible_person_email</key>
Same as above

2021-11-17 07:33 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="it"/>
```suggestion
		<text lang="it">Chi è il proprietario dei dati nel lungo periodo e può prendere decisioni sui dati dopo la partenza del ricercatore? Si prega di inserere il nome.</text>
```

2021-11-17 07:35 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="en">Who is the permanent project owner/data owner who can decide on the data after the researcher leaves? Please enter the name.</text>
Please specify "the researcher" ("der Forschende"). Did you mean the first author / the creator / den Urheber / the data responsible / the project coordinator / the principal investigator / the researcher**s** involved in the data creation or collection / ...?

2021-11-17 07:38 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="fr"/>
```suggestion
		<text lang="fr">Qui est le propriétaire des données dan le long terme et peut décider sur les données après le départ du chercheur&#8239;? Prière d'insérer un nom.</text>
```

2021-11-17 07:48 UTC, Zack-83 requested changes
Many thanks for this important pull request. Don't be offended from my many comments - I just wish you to make it perfect :)

2021-11-17 07:48 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="de">Wer ist der dauerhafter Besitzer der Daten, der nach dem Weggang des Forschenden über die Daten entscheiden kann? Bitte geben Sie den Name an.</text>
Is "owner" / "Besitzer" the right word? Or better "the responsible"? The legal status of data is not so clear...

2021-11-17 07:48 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="it"/>
```suggestion
		<text lang="it">Si prega di inserire l'indirizzo e-mail del proprietario dei dati nominato sopra.</text>
```

2021-11-17 07:48 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="fr"/>
```suggestion
		<text lang="fr">Prière d'insérer une adresse de courriel électronique du propriétaire des données nommé ci-dessus.</text>
```

2021-11-17 15:23 UTC, torsten-rathmann commented
Thank you for your pull request that at the same time opened my eyes to the fact that the already existing question "What investigated who the rights owner is?" is unfortunately (for reused data only) worded. However, your question apparently does not relate to the rights to the data, but rather to the factual control over the data.  Is that correct or what is the meaning of the term "permanent owner"? The purely legal view is especially not complete if the height of creation (Schöpfungshöhe) according to copyright law is not reached by the data.

2021-11-19 13:33 UTC, jmfrenzel commented on rdmorganiser/domain/rdmo.xml
> +	  <key>responsible_person_name</key>
```suggestion
	  <key>name</key>
```

2021-11-19 13:33 UTC, jmfrenzel commented on rdmorganiser/domain/rdmo.xml
> +	  <key>responsible_person_email</key>
```suggestion
	  <key>email</key>
```

2021-11-19 13:33 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">Eine ähnliche Fragestellung ist, was passiert bei Verlust der Zugangsdaten oder beispielsweise beim Ausscheiden/Ruhestand des Lehrstuhlinhabers? Dies sollte später über einen Workfl
```suggestion
		<help lang="de">Eine langfristige Kontaktperson ist der Ansprechpartner für das Datenzentrum oder das Archiv. Idealerweise kann diese Person Entscheidungen über die hinterlegten oder archivierten Daten treffen. Beispiele hierfür sind der Verlust von Zugangsdaten, die Vergabe von Zugangsberechtigungen oder z.B. das Ausscheiden des Ansprechpartners selbst. Dies sollte später über einen Workflow berücksichtigt werden.</help>
```

2021-11-19 13:33 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="de">Wer ist der dauerhafter Besitzer der Daten, der nach dem Weggang des Forschenden über die Daten entscheiden kann? Bitte geben Sie den Name an.</text>
```suggestion
		<text lang="de">Wer ist der langfristige Ansprechpartner, der über die Daten entscheiden kann? Bitte geben Sie den Name an.</text>
```

2021-11-19 13:33 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="en">A similar question is, what happens if the access data is lost or, for example, if the chair holder retires? This should be taken into consideration later on by means of a workflow.
```suggestion
		<help lang="en">A long-term contact person is the contact person to the data center or archive. Ideally, this person can make decisions about the deposited or archived data. Examples here are loss of access data, granting of access authorizations or, for example, the resignation/retirement of the contact person himself. This should be considered later via a workflow.</help>
```

2021-11-19 13:33 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="en">Who is the permanent project owner/data owner who can decide on the data after the researcher leaves? Please enter the name.</text>
```suggestion
		<text lang="en">Who is the long-term contact person who can make decisions about the data? Please specify the name.</text>
```

2021-11-19 13:39 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="de">Wer ist der dauerhafter Besitzer der Daten, der nach dem Weggang des Forschenden über die Daten entscheiden kann? Bitte geben Sie den Name an.</text>
Changed 'dauerhafter Besitzer der Daten' into 'langfristige Ansprechpartner'

2021-11-19 13:46 UTC, jmfrenzel commented
@Zack-83 @torsten-rathmann thank you for your review comments. I updated the the PR accordingly. I hope this make it more clear. 

@Zack-83 I'd be happy if you could contribute French and Italian.

2021-11-19 14:17 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="de">Bitte geben Sie die E-Mail-Adresse des oben gefragten dauerhaften Besitzers der Daten an.</text>
```suggestion
		<text lang="de">Bitte geben Sie die E-Mail-Adresse des oben genannten dauerhaften Ansprechpartners an.</text>
```

2021-11-19 14:17 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="en">Please provide the email address of the permanent owner of the data requested above.</text>
```suggestion
		<text lang="en">Please provide the email address of the permanent contact persona named above.</text>
```

2021-11-19 14:38 UTC, Zack-83 commented
Danke für die Verbesserungen.

Ich signalisiere noch eine kleine Inkohärenz bei den Zeilen 5587 bzw. 5591.

Der Verlust von Zugangsdaten sowie das Ausscheiden von Ansprechpartner sind keine Entscheidungen, sondern Situationen, die Entscheidungen erfordern. Anders als die Vergabe von Zugangsberechtigungen - die ist eine echte Entscheidung.

Mögliche Änderungsvorschläge:

> Beispiele hierfür sind die Vergabe von Zugangsdaten/Zugangsberechtigungen, die Optimierung des Speicherplatzes nach einer gewissen Bewahrungsfrist oder die Übergabe der Befügnisse an einen neuen Ansprechpartner.

> Solche eine Entscheidungsfähigkeit kommt in Einsatz beispielweise beim Verlust von Zugangsdaten, bei einer neuen Zugangsanfrage oder beim Ausscheiden des bisherigen Ansprechpartners.

Das fr/it werde ich nachher entsprechen aktualisieren.

2021-11-23 13:19 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">Eine langfristige Kontaktperson ist der Ansprechpartner für das Datenzentrum oder das Archiv. Idealerweise kann diese Person Entscheidungen über die hinterlegten oder archivierten D
```suggestion
		<help lang="de">Beispiele hierfür sind die Vergabe von Zugangsdaten/Zugangsberechtigungen, die Optimierung des Speicherplatzes nach einer gewissen Aufbewahrungsfrist oder die Übergabe der Befugnisse an einen neuen Ansprechpartner.

Solche Entscheidungen sind beispielsweise bei einem Verlust von Zugangsdaten, bei einer neuen Zugangsanfrage oder beim Ausscheiden des bisherigen Ansprechpartners erforderlich.
</help>
```

2021-11-23 13:19 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="en">A long-term contact person is the contact person to the data center or archive. Ideally, this person can make decisions about the deposited or archived data. Examples here are loss
```suggestion
		<help lang="en">Examples of these decisions include data access and authorization, the optimization of storage space after a certain retention period, or the transfer of authority to a new contact person.

Such decisions are necessary, for example, in the event of a loss of access data, a new access request or the departure of the previous contact person.</help>
```

2021-11-25 10:24 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +</help>
```suggestion
Solche Entscheidungen sind beispielsweise bei einem Verlust von Zugangsdaten, bei einer neuen Zugangsanfrage oder beim Ausscheiden des bisherigen Ansprechpartners erforderlich.</help>
```

2021-11-25 10:26 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +
```suggestion
```

2021-11-30 08:08 UTC, jmfrenzel commented
@Zack-83 Thanks for reviewing this! I wonder if the Italian and French needs to be adjusted as well? Otherwise, I think this can be merged.

2021-11-30 08:40 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +Des telles decisions peuvent être nécessaires dans le cas de perte des données d'accès, d'une nouvelle requête d'accès ou de retraite du référent précédent.</help>
```suggestion
		<help lang="fr">Exemples de telles decisions sont l'attribution d'un compte / de permis d'accès, la rationalisation de l'espace d'archiviation après un délai de garde défini, le transfert de l'autorité à un autre référent.

Des telles decisions peuvent être nécessaires dans le cas de perte des données d'accès, d'une nouvelle requête d'accès ou de retraite du référent précédent.</help>
```

2021-11-30 08:41 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +Tali decisioni possono essere necessarie in caso di perdita dei dati di accesso, bei nuove richieste di accesso o di ritiro della persona di riferimento precedente.</help>
```suggestion
		<help lang="it">Esempi di decisioni: l'assegnazione di un conto o di diritti di accesso, la razionalizzazione dello spazio di archivio dopo una scadenza di conservazione definita, la trasmissione della sovranità a un'altra persona di riferimento.

Tali decisioni possono essere necessarie in caso di perdita dei dati di accesso, di nuove richieste di accesso o di ritiro della persona di riferimento precedente.</help>
```

2021-11-30 08:48 UTC, Zack-83 approved these changes

2021-11-30 09:49 UTC, merged