Neuer Fragebogen DFG Chemie
rdmorganiser/rdmo-catalog pull request #161
Opened 2022-11-03 14:05 UTC by laura-tte

Entwicklung des Fragebogens im Rahmen des Projektes "eHumanities - interdisziplinär". Bereits in RDMO-Instanzen der FAU Erlangen-Nürnberg und der LMU München im Einsatz. 
Pull Request umfasst: XML-Datei mit Fragen und ReadMe-Datei 
Für Rückfragen: fdm@ub.uni-muenchen.de

2022-11-15 15:22 UTC, Zack-83 commented
Fehlendes Attribut: `https://fdm-bayern.org/eHumanities/domain/project/dataset/documentation/where`

![grafik](https://user-images.githubusercontent.com/37865804/201956905-90ef1871-e8e1-42b0-b72e-02265f1824d5.png)

Lass uns am 24.11. diskutieren, ob es mit dem jetzigen Präfix oder mit dem zentralen Präfix `https://rdmorganiser.github.io/terms` angenommen werden soll.

2022-11-15 15:35 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/dfg-chemie/Fragenkatalog_Chemie.md
> +> Textfeld
```suggestion
> Widget: Textfeld
```
Vielleicht auch anderweitig

2022-11-15 15:38 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/dfg-chemie/dfg_Chemie.xml
> +		Bei DFG-Anträgen sollten Mittel zur Datenpublikation in Datenrepositorien nicht bei der Open-Access-Unterstützung beantragt werden, sondern unter der &lt;a href=&quot;https://www.dfg.de/foerderung/
```suggestion
		<help lang="en">The effort is taken into account in the evaluation of the requested project-specific funds. In addition to direct costs, such as costs for storage space in a data archive, personnel costs, for example 3 person-months for a computer scientist programming a mapping between data formats, should also be cited.

In DFG proposals, funds for data publication in data repositories should not be requested under OA support, but under the &lt;a href=&quot;https://www.dfg.de/foerderung/grundlagen_rahmenbedingungen/forschungsdaten/beantragbare_mittel/index.html&quot; target=&quot;_blank&quot;&gt;heading &quot;Other costs&quot; for the use of established infrastructures&lt;/a&gt;. In doing so, the request must indicate the differentiation of these services from the basic services (&quot;Grundausstattung&quot;).</help>								 
		<text lang="en">What are the costs associated with data management in the project?</text>
		<default_text lang="en"/>
		<verbose_name lang="en"/>
		<verbose_name_plural lang="en"/>
		<help lang="de">Der Aufwand wird bei der Bewertung der beantragten, projektspezifischen Mittel berücksichtigt. Neben direkten Kosten, wie etwa Kosten für Speicherplatz in einem Datenarchiv, sollten auch Personalkosten, beispielsweise 3 Personenmonate für einen Informatiker, der ein Mapping zwischen Datenformaten programmiert, angeführt werden.

Bei DFG-Anträgen sollten Mittel zur Datenpublikation in Datenrepositorien nicht bei der Open-Access-Unterstützung beantragt werden, sondern unter der &lt;a href=&quot;https://www.dfg.de/foerderung/grundlagen_rahmenbedingungen/forschungsdaten/beantragbare_mittel/index.html&quot; target=&quot;_blank&quot;&gt;Rubrik &quot;Sonstige Kosten&quot; zur Nutzung etablierter Infrastrukturen&lt;/a&gt;. Dabei muss aus dem Antrag die Abgrenzung dieser Dienste von der Grundausstattung hervorgehen.</help>									
```

2022-11-29 07:55 UTC, Zack-83 commented
> Fehlendes Attribut: `https://fdm-bayern.org/eHumanities/domain/project/dataset/documentation/where`
> 
> ![grafik](https://user-images.githubusercontent.com/37865804/201956905-90ef1871-e8e1-42b0-b72e-02265f1824d5.png)
> 
> Lass uns am 24.11. diskutieren, ob es mit dem jetzigen Präfix oder mit dem zentralen Präfix `https://rdmorganiser.github.io/terms` angenommen werden soll.

Das Attribut existiert wohl: https://github.com/rdmorganiser/rdmo-catalog/blob/4b62cc83157d56c2546f5e76d5940ac8cd51fc5b/rdmorganiser/domain/rdmo.xml#L451

2022-11-29 07:59 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/dfg-chemie/dfg_Chemie.xml
> +		<attribute dc:uri="https://fdm-bayern.org/eHumanities/domain/project/dataset/documentation/where"/>
```suggestion
		<attribute dc:uri="https://rdmorganiser.github.io/terms/domain/project/dataset/documentation/where">
```

2022-11-29 08:32 UTC, Zack-83 requested changes
Hallo Laura, wie gesagt:

- Fragenkatalog sieht gut aus, nur die Referenz zum Attribut `documentation/where` sollte korrigiert werden
- Dokumentation: kurze Anleitung, dann je Frage ggf. URI + Text + Attribut + Optionensatz + Widget, ggf. als Tabelle

2022-12-22 13:17 UTC, laura-tte commented on shared/ub_fau_erlangen_nuernberg/dfg-chemie/Fragenkatalog_Chemie.md
> +> Textfeld
Den Zusatz "Widget: " habe ich im neuen Commit an allen Stellen eingefügt.

2022-12-22 13:18 UTC, laura-tte commented on shared/ub_fau_erlangen_nuernberg/dfg-chemie/dfg_Chemie.xml
> +		<attribute dc:uri="https://fdm-bayern.org/eHumanities/domain/project/dataset/documentation/where"/>
Die zwei lokalen Attribute habe ich im neuen Commit durch die RDMO-Attribute ersetzt.

2022-12-22 13:21 UTC, laura-tte commented
Hallo Giacomo, ich habe deine Empfehlungen in dem neuen Commit umgesetzt. Es gab noch zwei lokale Attribute, die ich durch RDMO-Attribute ersetzt habe. Außerdem habe ich die Platzhalter für Französisch entfernt. 

Die Dokumentation habe ich besprochen gekürzt und am Anfang findet man jetzt auch eine kurze Erläuterung zum Fragebogen. 

Entschuldige, dass die Überarbeitung so lange gedauert hat!

2022-12-22 13:23 UTC, laura-tte commented on shared/ub_fau_erlangen_nuernberg/dfg-chemie/dfg_Chemie.xml
> +		Bei DFG-Anträgen sollten Mittel zur Datenpublikation in Datenrepositorien nicht bei der Open-Access-Unterstützung beantragt werden, sondern unter der &lt;a href=&quot;https://www.dfg.de/foerderung/
Was genau hat sich hier geändert? Nur die Einrückung? Falls ja, kann das gerne übernommen werden.

2022-12-23 06:45 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/dfg-chemie/dfg_Chemie.xml
> +		Bei DFG-Anträgen sollten Mittel zur Datenpublikation in Datenrepositorien nicht bei der Open-Access-Unterstützung beantragt werden, sondern unter der &lt;a href=&quot;https://www.dfg.de/foerderung/
Ja, genau, die Einrückung. Kannst du es übernehmen? Ich habe auf eurem Repo `[UB-LMU:FDM-Bayern](https://github.com/UB-LMU/rdmo-catalog/tree/FDM-Bayern)` keine Schreibrechte

2022-12-23 06:49 UTC, Zack-83 approved these changes
Gut gemacht! Die Einrückung ist eine Kleinigkeit - die justiere ich nachträglich

2022-12-23 06:50 UTC, merged