Add MATH+ questionset
rdmorganiser/rdmo-catalog pull request #162
Opened 2022-11-08 15:48 UTC by Metamost

This is the question set used in the DFG Excellence Cluster The Berlin Mathematics Research Center MATH+ (EXC-2046/1, project ID: 390685689)
It was derived from the original RDMO questionnaire and reduced so that it takes no longer than 20 minutes to answer. Nevertheless, it maps the recommendation for handling research data from the DFG homepage.: https://www.dfg.de/en/research_funding/principles_dfg_funding/research_data/index.html

2022-11-08 17:50 UTC, jochenklar commented
Hi @Metamost ,

One thing: `https://rdmorganiser.github.io/terms/domain/project/dataset/sharing/uri` does not exist (yet), there is `https://rdmorganiser.github.io/terms/domain/project/dataset/storage/uri` and `https://rdmorganiser.github.io/terms/domain/project/dataset/uri` though.

Otherwise, the import went fine!

2022-11-10 08:39 UTC, jochenklar approved these changes

2022-11-10 08:39 UTC, jochenklar commented
Looks good, @triole @Zack-83 please have a look.

2022-11-10 10:30 UTC, Zack-83 commented on shared/MATH+/mathplus_questions.xml
> +		<dc:comment>Dieser Fragenkatalog ist eine Anpassung an die Erfordernisse der mathematischen DMP im Umfeld der Berliner Mathematik. Er basiert in großen Teilen auf dem DFG Fragenkatalog des Projekts
```suggestion
		<dc:comment>Dieser Fragenkatalog ist eine Anpassung an die Erfordernisse der mathematischen DMP im Umfeld der Berliner Mathematik. Er basiert in großen Teilen auf dem DFG-Fragenkatalog aus dem Projekt FoDaKo - Forschungsdatenmanagement und digitale Langzeitarchivierung in Kooperation (https://github.com/rdmorganiser/rdmo-catalog/tree/master/shared/fodako). Er ist eine Teilmenge des Katalogs "RDMO" und enthält nur die Fragen, die die Anforderungen in den "Leitlinien zum Umgang mit Forschungsdaten" der DFG, http://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten, abdecken. Die Fragen sind somit ausgesucht für Datenmanagementpläne, die Förderanträgen an die Deutsche Forschungsgemeinschaft (DFG) beigelegt werden sollen und keine fachspezifischen Zusatzanforderungen zu erfüllen haben.</dc:comment>
```

2022-11-10 10:33 UTC, Zack-83 commented on shared/MATH+/mathplus_questions.xml
> +                                Data in Biodiversity Research&lt;/a&gt;
```suggestion
- &lt;a href="http://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/guidelines_biodiversity_research.pdf" target=_blank"&gt;Guidelines on the Handling of Research Data in Biodiversity Research&lt;/a&gt;
```

2022-11-10 10:36 UTC, Zack-83 commented
Looks good. The two conditions might be unified in only one file or even integrated into the main conditions file

2022-11-10 17:41 UTC, Metamost commented
Unifying the two conditions is absolutely fine. What is the main conditions file? If that means integrating it in the official RDMO conditions file I would be delighted. 
And may I suggest to have a look at the attribute where our users can store the link or identifier to their published dataset? /MATH+/mathplus_domain_sharing_uri.xml  
It seems to me that could be of interest to the community as well. 
And I'll thank you tomorrow online for correcting the name and the unnecessary linebreak : ).

2022-11-11 08:24 UTC, Zack-83 commented
> Unifying the two conditions is absolutely fine. What is the main conditions file? If that means integrating it in the official RDMO conditions file I would be delighted. And may I suggest to have a look at the attribute where our users can store the link or identifier to their published dataset? /MATH+/mathplus_domain_sharing_uri.xml It seems to me that could be of interest to the community as well. And I'll thank you tomorrow online for correcting the name and the unnecessary linebreak : ).

The main conditions file is https://github.com/rdmorganiser/rdmo-catalog/blob/master/rdmorganiser/conditions/rdmo.xml

To integrate your creations into the main RDMO files we should get approval by the community. We can achieve it the latest by the next meeting of the _UAG Redaktionsprozesse_, the 24.11.
You're welcome to join the discussion here: https://rdmo.slack.com/archives/C03GYKPR98C/p1668154257049909

2022-11-29 08:27 UTC, Zack-83 requested changes
Hallo Tim, wie besprochen hier meine Empfehlung:

- Attribut & Bedingung ins zentrale Repo schieben #164
- Deinen Fragenset anpassen und die drei überflüssigen Dateien löschen
- Merge Request wird ausgeführt

2022-12-19 06:43 UTC, Zack-83 approved these changes

2022-12-19 06:43 UTC, Zack-83 commented
Gut gemacht!

2022-12-19 06:45 UTC, merged