DFG-Checklisten-Implementierung
rdmorganiser/rdmo-catalog pull request #173
Opened 2023-01-19 07:32 UTC by Zack-83

2023-01-26 13:35 UTC, Zack-83 commented on rdmorganiser/options/rdmo.xml
> +
```suggestion
```

2023-02-09 15:59 UTC, Zack-83 commented on rdmorganiser/questions/DFG-Checkliste.xml
> +	</question>
```suggestion
```

2023-02-13 16:27 UTC, jmfrenzel requested changes
Translation work is not done. The English version is not in sync with the German.

2023-02-23 08:21 UTC, jmfrenzel requested changes
It looks good from the high level perspective. This is without going into the details of every text in the catalog ect. 

I suggest one more change before merging.
 
*  In the README.md the Checklist catalog is listed to be located under shared catalogs, but they are located in the 'rdmorganiser' directory. I suggest that we keep it in place and change the README.md accordingly.

2023-02-27 14:38 UTC, Zack-83 commented
Prefixes replaced. Import works.

Possible additional changes (let's talk about, @jmfrenzel ):

* remove `dfg_` where not strictly necessary;
* harmonise optionset keys (some end with `_options`, others do not);
* reconciliate the competing optionsets:
  * `dataset_size_options` and `dfg_dataset_size_options`
  * `preservation_motivation_options` and `dfg_preservation_motivation_options`
  * `control_tools` and `control_tools_long`

2023-02-28 16:16 UTC, jmfrenzel approved these changes
looks good to me

2023-02-28 16:17 UTC, merged