Korrekturen
rdmorganiser/rdmo-catalog pull request #176
Opened 2023-01-26 18:02 UTC by Sabine-Schoenau

2023-02-13 16:25 UTC, jmfrenzel requested changes
Can not judge on the content of the files. Technically they look good. 

Before merging I would be great if  README was provided for nfdi4ing shared catalogs documenting 
* the content, e.g. sub directory content and file content such as catalog, conditions ect. 
* compatibility or dependency with / on  community content from the  `rdmorganiser` directory, e.g. domain options ect.

2023-03-08 13:33 UTC, Zack-83 commented
> Can not judge on the content of the files. Technically they look good.
> 
> Before merging I would be great if README was provided for nfdi4ing shared catalogs documenting
> 
>     * the content, e.g. sub directory content and file content such as catalog, conditions ect.
> 
>     * compatibility or dependency with / on  community content from the  `rdmorganiser` directory, e.g. domain options ect.

Beispiel: https://github.com/rdmorganiser/rdmo-catalog/blob/master/shared/Max-Planck-Digital-Library/Software-Management-Plan/readme.md

2023-03-13 09:37 UTC, Zack-83 commented on shared/nfdi4ing/NFDI4Ing_template/NFDI4Ing_Vorlage.xml
> +		<help lang="de">Als Grundlage für den Katalog dient ebenfalls die DFG-Checkliste vom 21.12.2021 mit 23 Fragen. Angereichert wurde das Template mit ingenieurspezifischen Inhalten.</help>
```suggestion
		<title lang="en">NFDI4Ing_template</title>
		<help lang="en">The basis for the catalog is also the DFG checklist of December 21, 2021 with 23 questions. The template was enriched with engineer-specific content.</help>
		<title lang="de">NFDI4Ing_Vorlage</title>
		<help lang="de">Als Grundlage für den Katalog dient ebenfalls die DFG-Checkliste vom 21.12.2021 mit 23 Fragen. Angereichert wurde das Template mit ingenieurspezifischen Inhalten.</help>
```

2023-03-13 09:42 UTC, Zack-83 approved these changes

2023-03-13 09:44 UTC, Zack-83 approved these changes

2023-03-13 14:46 UTC, jmfrenzel approved these changes
Approval form my side as a Read-me file has been provided. 

I noticed that one question was removed. For me that removal looks unintended.

2023-03-13 14:46 UTC, jmfrenzel commented on shared/nfdi4ing/NFDI4Ing_template/NFDI4Ing_Vorlage.xml
> -	<question dc:uri="https://rdmo.nfdi4ing.de/terms/questions/NFDI4Ing_Vorlage/exchange_access/archiving/archiving_yes">
This question has been removed.

2023-03-13 15:49 UTC, merged