Renamefiles
rdmorganiser/rdmo-catalog pull request #23
Opened 2021-03-01 12:32 UTC by Zack-83

Nach der Issue #22 
Ich habe die Dateien im Hauptverzeichnis (`rdmorganiser`) umbenannt und verschoben.
Für diejenige aus der Community (im Ordner `shared`) ist vielleicht besser, dass die "Urheber" es selber machen.

2021-03-01 13:37 UTC, Zack-83 commented
Auch Issue #19 adressiert

2021-03-22 11:30 UTC, jochenklar approved these changes

2021-03-22 11:31 UTC, jochenklar commented
Ok, @jmfrenzel damit wir hier mal weiter kommen würde ich sagen das wir noch auf ein Häckchen von @triole oder @Freund-J warten und das dann mergen.

2021-03-22 11:43 UTC, Zack-83 commented
> 
> Ok, @jmfrenzel damit wir hier mal weiter kommen würde ich sagen das wir noch auf ein Häckchen von @triole oder @Freund-J warten und das dann mergen.

Oder @jmfrenzel selbst :D

2021-03-22 12:36 UTC, Freund-J approved these changes

2021-03-22 12:44 UTC, torsten-rathmann commented
Mit den ersten 7 Commits bin ich einverstanden. Die anderen verstehe ich nicht. Warum soll beispielsweise nach Commit Nr. 10 snf.xml künftig rdmorganiser/snf.xmlrdmo-questions-snf.xml mit zwei Punkten im File-Namen heißen? Und wofür ist dann noch Commit Nr. 12

Rename snf.xml to rdmo-questions-snf.xml?

2021-03-22 12:55 UTC, Zack-83 commented
Richtig, Commit 10 ist leider schief gelaufen (beim Kopieren und Einfügen habe ich den falschen Präfix gelassen statt zu überschreiben) und deswegen musste ich mit Commit 12 es wieder gut machen.
Leider GitHub vergisst (und vergibt) nichts. Hoffentlich sind die Dateien im Endzustand korrekt.

2021-03-22 13:15 UTC, torsten-rathmann commented
Lassen sich die Commits nicht aus einer zuvor erstellten Textdatei mit Copy-and-Paste ins GitHub bringen? In der könnte der Endzustand vorformuliert sein.

2021-03-22 13:24 UTC, jmfrenzel requested changes
I'm not quiet happy with the file rename and reorganization of the structure. The change breaks (automated) deployment routines and users have adjust. 
@jochenklar convinced me that this change is necessary as it reverts to a similar file structure being used earlier f32e077672e4d80fd472ab2fcbd7d77f47534f02 and which many users seem to prefer.
But as a result of the breaking change by the current PR, we need to inform users about the new structure as this PR will merge into 'master' which is production. So  I strongly suggest starting with versioning (semver) to give users of 'rdmo-catalog' a better understanding of what to expect. 

Minor: Commit history could be cleaned as  168d39c67f07b009daf0f64278d25275bb2e5070 corrects for  8c11dcb98d1575f9acc351fa78fc777fea280488

2021-03-22 15:55 UTC, jochenklar commented
@jmfrenzel ok, we could use the same `master`/`dev` branch setup as we do for rdmo.

2021-03-22 16:04 UTC, jmfrenzel commented
Sounds good to me


On Mon, Mar 22, 2021, 4:55 PM Jochen Klar ***@***.***> wrote:

> @jmfrenzel <https://github.com/jmfrenzel> ok, we could use the same master
> /dev branch setup as we do for rdmo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rdmorganiser/rdmo-catalog/pull/23#issuecomment-804180401>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHJNZAXZRDCKYSJVMONB2ALTE5SAHANCNFSM4YMOOUFQ>
> .
>

2021-03-22 16:10 UTC, jochenklar commented
@torsten-rathmann ich kann die überflüssigen commit entfernen, dann könnten wir mit dem PR hier weitermachen oder? ich würde ungern wieder von vorne anfangen.

2021-03-22 18:00 UTC, torsten-rathmann commented
Eine Fehlbedienung, ich bitte um Verzeihung!

2021-03-22 18:23 UTC, torsten-rathmann approved these changes

2021-03-26 11:30 UTC, closed without merging