Template developed for CRC1382
rdmorganiser/rdmo-catalog pull request #24
Opened 2021-03-01 15:46 UTC by LukasCBossert

This is a template which has been created for a medicine-based CRC.

2021-03-15 13:41 UTC, Zack-83 requested changes
Gut gemacht, aber ich empfehle ein paar Punkte bevor dem _Merge_ zu revidieren

2021-03-15 13:41 UTC, Zack-83 commented on shared/sfb1382_gut-liver-axis/README.md
> +* https://rdmorganiser.github.io/terms/options/yes_no_not_yet
I would say that these are new option_**sets**_.
Eight of them seem to me very much application-specific. From one of the latest conversations I deduce they should correspondingly have a new prefix.
The other three are general enough, so they could be welcome with the `https://rdmorganiser.github.io/` prefix.

2021-03-15 13:41 UTC, Zack-83 commented on shared/sfb1382_gut-liver-axis/README.md
> +* https://rdmorganis+er.github.io/terms/conditions/personal_data
`https://rdmorganis+er.github.io/` --> typo / Tippfehler (ein `+` zu viel)

2021-03-15 13:41 UTC, Zack-83 commented on shared/sfb1382_gut-liver-axis/SFB1382_options.xml
> +		<conditions/>
I am worried that a whitespace in a key or in a path might produce problems. (The same applies to the following options.)

2021-03-18 15:09 UTC, LukasCBossert commented
Thanks for the feedback. I will work on the mentioned topics and request for a new merge.

2021-03-18 15:09 UTC, closed without merging