RDMO catalog changes
rdmorganiser/rdmo-catalog pull request #27
Opened 2021-03-11 12:26 UTC by laura-tte

Changes include:
- typos
- broken links
- minor additions
- added missing translations

2021-03-15 13:23 UTC, Zack-83 approved these changes

2021-03-15 13:23 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +			beschäftigten Person).</help>
Ich nehme an, an der Stelle der so vielen Leerzeilen sollte wieder `vollzeit-` stehen.

2021-03-22 11:45 UTC, Zack-83 commented
This merge request would also solve #19

2021-03-22 14:58 UTC, jmfrenzel requested changes

2021-03-22 14:58 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +
Might want to remove blank lines?

2021-03-22 14:58 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">(Diese Frage stammt ursprünglich aus dem Horizon 2020 FAIR Datenmanagementplan.)</help>
This seems like a comment for an editor of the catalog. Would you please provide why this is important to be presented in the rdmo interview?

2021-03-25 10:40 UTC, laura-tte commented on rdmorganiser/questions/rdmo.xml
> +
I think the blank lines were removed with the last commit.

2021-03-25 17:47 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">(Diese Frage stammt ursprünglich aus dem Horizon 2020 FAIR Datenmanagementplan.)</help>
diese Anmerkung war im Katalog schon vorhanden, aber nur auf Englisch

2021-03-26 11:35 UTC, jochenklar commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">(Diese Frage stammt ursprünglich aus dem Horizon 2020 FAIR Datenmanagementplan.)</help>
@jmfrenzel wir haben grade besprochen, das wir das erstmal mergen und dann in einem neuen PR in den comment schicken. Du kannst also hier mergen.

2021-03-26 12:42 UTC, jmfrenzel approved these changes

2021-03-26 12:48 UTC, merged