Four new conditions
rdmorganiser/rdmo-catalog pull request #28
Opened 2021-03-25 17:54 UTC by Zack-83

2021-03-26 10:06 UTC, torsten-rathmann commented
This pull request contains besides new conditions a change of the <source> of an existing condition. For my review I need two hints from experts:

1.  Do catalogs using the unchanged condition still work?
2. Is the <source> in the XML the same as the "source attribute" in the RDMO readthedocs?

2021-03-26 10:13 UTC, torsten-rathmann commented
The pull request rises a general question too. Are future catalog authors asked to use all existing condition matching their question / question sets in the catalog?

I think this isn't the case. My opinion is that they have the freedom to ignore a condition. The discussion concerning new conditions would be much more difficult if we expect catalog writers to use them, of course.

2021-03-26 11:53 UTC, jochenklar commented on rdmorganiser/conditions/rdmo.xml
> +		<target_text>yes</target_text>
This should be 0 or 1, right?

2021-03-26 11:55 UTC, jochenklar commented on rdmorganiser/conditions/rdmo.xml
> +		<relation>contains</relation>
This should be `eq`

2021-04-14 10:33 UTC, torsten-rathmann approved these changes

2021-05-17 16:12 UTC, jmfrenzel requested changes
Please add an overview to the PR description, wich we need for the change log  later.

e.g. like https://github.com/rdmorganiser/rdmo-catalog/pull/29#issue-600992941

| Change                            | Key                                 | Attribute (Source) | Remarks     | Proof result      |
| --------------------------------- | ----------------------------------- | ---------- | ----------- | ----------------- |
| [new/edited/removed] | [key f the condition]  | [The Attribute this condition is evaluating] |  |  |

2021-05-17 18:46 UTC, jmfrenzel approved these changes
Seems ok to me.

2021-05-17 18:48 UTC, merged