Formatting + one more question
rdmorganiser/rdmo-catalog pull request #30
Opened 2021-03-26 16:57 UTC by Zack-83

| Change                          | Path                                                      | Remarks                 |
| ------------------------------- | --------------------------------------------------------- | ----------------------- |
| New question                    | general/topic-research_field/name                         | name of RDM responsible |
| Link within question changed    | data-usage/data-sharing-and-re-use-publication/conditions |                         |
| Minor changes (newlines, lists) | …                                                         |                         |
| French & Italian translation    | …                                                         |                         |

2021-04-14 11:01 UTC, torsten-rathmann commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">Immer mehr Hochschulen und wissenschaftliche Einrichtungen verabschieden Leitlinien oder Richtlinien (oft auch als &quot;Policies&quot; bezeichnet) zum Forschungsdatenmanagement.
href=&quot; will not work, the same with target=&quot;

2021-04-14 11:05 UTC, torsten-rathmann commented on rdmorganiser/questions/rdmo.xml
> +Diese enthalten unter anderem Empfehlungen und/oder Vorgaben zum Umgang mit Forschungsdaten, die die Wissenschaftlerinnen und Wissenschaftler der Einrichtung beachten sollten oder müssen (je nach Gra
again

2021-04-14 11:10 UTC, torsten-rathmann commented on rdmorganiser/questions/rdmo.xml
> +Beispiele sind die &lt;a href=&quot;https://www.dfg.de/foerderung/antrag_gutachter_gremien/antragstellende/nachnutzung_forschungsdaten/index.html&quot; target=&quot;_blank&quot;&gt;DFG-Leitlinien zum
again href=\&quot; and target=\&quot;. Have the """ been replaced automatically?

2021-04-15 07:52 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">Immer mehr Hochschulen und wissenschaftliche Einrichtungen verabschieden Leitlinien oder Richtlinien (oft auch als &quot;Policies&quot; bezeichnet) zum Forschungsdatenmanagement.
The substitution was done in the merge request #34 by @jmfrenzel

2021-04-19 07:13 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">Immer mehr Hochschulen und wissenschaftliche Einrichtungen verabschieden Leitlinien oder Richtlinien (oft auch als &quot;Policies&quot; bezeichnet) zum Forschungsdatenmanagement.
@torsten-rathmann can you please provide more detail on your comment. Where do you find these expressions not working and how can one reproduce this behavior. This is of much interest, since these expressions are used in many catalogs.

2021-04-19 12:01 UTC, torsten-rathmann commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">Immer mehr Hochschulen und wissenschaftliche Einrichtungen verabschieden Leitlinien oder Richtlinien (oft auch als &quot;Policies&quot; bezeichnet) zum Forschungsdatenmanagement.
I was wrong, sorry! href=&quot; is interpreted correctly.

2021-04-19 12:04 UTC, torsten-rathmann approved these changes

2021-05-07 12:13 UTC, Zack-83 commented
solves issue #5

2021-05-17 19:34 UTC, jmfrenzel requested changes
So far the PR looks good. 
* Please find some minor suggestions inline.
* What is not clear to me is the propose of the many newlines that are introduced within texts and help texts.

2021-05-17 19:34 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="en">How are the origin, quality, etc. of the data documented?</help>
How is the origin and quality of the data documented.

2021-05-17 19:34 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +	<question dc:uri="https://rdmorganiser.github.io/terms/questions/rdmo/general/topic-research_field/name">
There is an existing question in master that uses the same attribute, see https://github.com/rdmorganiser/rdmo-catalog/blob/b7be83b2fe901cf37a0594e003e5f7dfbcc059cc/rdmorganiser/questions/rdmo.xml#L267 
There has been a fix earlier this year, which was removing <question dc:uri="https://rdmorganiser.github.io/terms/questions/rdmo/general/topic-research_field/name">
see https://github.com/rdmorganiser/rdmo-catalog/pull/20

2021-05-17 19:34 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="en">More and more universities and scientific institutions adopt research data management policies.
Please revert the line break as it is arbitrary and does not add new functionality. Pleas consider the same issue for many more entries below.

2021-05-17 19:34 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="en">Which funding programme does the project get financing from?</text>
I would suggest to use the following text "In which funding program is the project funded?"

2021-05-17 19:34 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="en">What are the personnel costs associated with the the creation of metadata and context information in the project?</text>
the the ??

2021-05-17 19:34 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
>  		<text lang="en">What are the personnel costs for data management associated with the the usage of data in the project?</text>
the the

2021-05-18 07:53 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="en">Which funding programme does the project get financing from?</text>
```suggestion
		<text lang="en">In which funding program is the project funded?</text>
```

2021-05-18 07:53 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<text lang="en">What are the personnel costs associated with the the creation of metadata and context information in the project?</text>
```suggestion
		<text lang="en">What are the personnel costs associated with the creation of metadata and context information in the project?</text>
```

2021-05-18 07:53 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
>  		<text lang="en">What are the personnel costs for data management associated with the the usage of data in the project?</text>
```suggestion
		<text lang="en">What are the personnel costs for data management associated with the usage of data in the project?</text>
```

2021-05-18 07:53 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="en">More and more universities and scientific institutions adopt research data management policies.
We can talk about it :)

The additional line breaks are meant to improve the legibility for anyone visualizing the HTML source or the CSV table. Specially for long text chunks with many paragraphs they help recognizing the structure, translating and comparing different languages.

I admit that the divisions are somehow arbitrary, but in the previous version the text was too wide and also arbitrarily broken. An old rule of programmers states not to make lines longer than 80 characters - I did not follow it strictly.

In my opinion the line breaks don't have any consequences in the rendering of the HTML output.

2021-05-18 07:55 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="en">How are the origin, quality, etc. of the data documented?</help>
Are you sure? To my feeling "the origin and the quality" is plural, so they _are_ documented

2021-05-18 08:08 UTC, Zack-83 reviewed
Many thanks for your comments and suggestions, Johannes. I tried to address them.
* Concerning newlines: let's talk about.
* The French and Italian text corresponds the one in the other merge #32 . The Italian was reviewed and approved by @dario-pilori and the French was reviewed by the partner in Lyon, Yonny Cardenas (per e-mail, outside GitHub)

2021-05-18 08:08 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +	</question>
```suggestion
```

2021-05-18 08:20 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="en">How are the origin, quality, etc. of the data documented?</help>
```suggestion
		<help lang="en">How are the origin and the quality of the data documented?</help>
```

2021-07-21 15:18 UTC, merged

2021-07-22 06:20 UTC, Zack-83 commented
@jmfrenzel @torsten-rathmann @jochenklar @dario-pilori

In der Tat hat sich doch ein doppeltes Pull Request erzeugt (vgl. #58) und automatisch gemerged. Es war nicht so gemeint, ich wollte nicht an allen vorbei vorpreschen!!!

Können wir ihr vorläufig damit leben, oder wollt ihr es lieber rückgängig machen?

> Hallo Jungs,
> ich wollte mal diesen alten Pull Request auf Vordermann bringen und dafür ihn mit dem jetzigen Stand von dev verglichen.
> Meine Absicht war, einen Merge von dev in meinen Branch Zack83-patch-3 auszuführen, dann wieder darauf schauen und demnächst den Pull Request ausführen. Die 28 entstandenen Konflikte wurden per Hand gelöst.
> Es ist mir nicht ganz klar, was GitHub damit angestellt hat. Wurden gleichzeitig beide Zweige aktualisiert?
> Zum Glück ist der entstandene Commit sehr überschaubar, mit nicht mehr als 20 Mini-Änderungen (meistens Gänsefüsschen, kleinere ortografische Änderungen, gelegentliche aber schon bestätigte italienische Übersetzungen).
> Wenn ihr mir einen kurzen Feedback 👍 👎 gebt, dann kann ich mit dem echten (deutlich längeren aber nun sauberen) Merge weitermachen.

2021-07-23 17:03 UTC, Zack-83 commented
newlines deleted, just quotes escaped and French/Italian translation added