Files for localisation of RDMO into other languages
rdmorganiser/rdmo-catalog pull request #32
Opened 2021-03-29 08:33 UTC by Zack-83

Contains a R script and TSV translation memories

2021-04-12 07:00 UTC, dario-pilori approved these changes
I corrected some typos, but everything else looks fine to me. I guess that, in Italian, "Personenmonaten" is more often translated into "mesi-uomo" instead of "persone-mesi", but grammatically they're both correct.

2021-04-15 11:07 UTC, Zack-83 commented on localisation/rdmo-options-localisation.tsv
> +/rdmo/option[66]/text	Verschlüsselung der Daten	Cryptography of the data	cryptage des données	criptaggio dei dati
avrei preferito una parola descrivente l'azione ma non la trovo (Esiste "crittazione?")

2021-05-17 17:29 UTC, jmfrenzel requested changes
The tool is of great need. 

I wonder if you can add an README.md file with a short documentation how this tool should be used.
Is there a workflow automatize translations using this tool.

See also inline comments.

2021-05-17 17:29 UTC, jmfrenzel commented on localisation/rdmo-translation.R
> +setwd("C:/Users/lanza01/Desktop/lavori in corso/RDMO 2020")
This seems to be a local path. Do we need this here?

2021-05-18 10:59 UTC, Zack-83 commented on localisation/rdmo-translation.R
> +setwd("C:/Users/lanza01/Desktop/lavori in corso/RDMO 2020")
```suggestion
# setwd("C:/Users/MYPATH")    # enter path
```

2021-05-18 11:22 UTC, Zack-83 commented
> 
> 
> The tool is of great need.
> 
> I wonder if you can add an README.md file with a short documentation how this tool should be used.
> Is there a workflow automatize translations using this tool.
> 
> See also inline comments.

I added the README.md . The workflow is not automatic yet and requires several manual steps by the user. There is still much room for improvement.

2021-05-27 15:42 UTC, jmfrenzel requested changes
The changes seem ok to me. 

However following the instructions  `localisation/README.md` I  understand that  `*.tsv` files are being created from "source" xml. As a consequencewe do not need `tsv` files in version control. I suggest to remove them from the PR

2021-05-31 17:08 UTC, Zack-83 commented
> 
> 
> The changes seem ok to me.
> 
> However following the instructions `localisation/README.md` I understand that `*.tsv` files are being created from "source" xml. As a consequencewe do not need `tsv` files in version control. I suggest to remove them from the PR

We can remove them at this stage. In the future we might need them again if we have to communicate with translators who cannot run scripts.
Hey @dario-pilori, how can I remove a file from GitHub?

2021-06-01 08:21 UTC, dario-pilori commented
> Hey @dario-pilori, how can I remove a file from GitHub?
I just removed it using command-line git (git rm <file>). I committed this change and pushed back to this branch.

2021-06-01 09:44 UTC, jmfrenzel commented
> > The changes seem ok to me.
> > However following the instructions `localisation/README.md` I understand that `*.tsv` files are being created from "source" xml. As a consequencewe do not need `tsv` files in version control. I suggest to remove them from the PR
> 
> We can remove them at this stage. In the future we might need them again if we have to communicate with translators who cannot run scripts.

This is totally fine, as long as these files are removed before the PR is being merged.

2021-06-01 09:49 UTC, merged