Consideration of DFG Recommendations: Proposal for 6 New Attributes
rdmorganiser/rdmo-catalog pull request #41
Opened 2021-04-23 07:25 UTC by torsten-rathmann

| New Attribute | For Question | Recommended in |
|---------------------|------------------|----------|
| project/dataset/documentation | Which components of the data documentation are available together with the dataset? | many in https://www.dfg.de/foerderung/antrag_gutachter_gremien/antragstellende/nachnutzung_forschungsdaten/ |
| project/dataset/documentation/where | Where is the data documentation provided? | https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/fachkollegium112_forschungsdatenmanagement_de_1811.pdf |
| project/dataset/documentation_on_request | Which components of the data documentation are provided on request?                                                | https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/richtlinien_forschungsdaten_bildungsforschung.pdf |
| project/dataset/ipr/status | Which rights have been obtained or what is the status of the rights collection? | https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/guidelines_review_board_linguistics_corpora.pdf |
| project/dataset/reuse_existing | Are already existing, similar research data available and why is their subsequent use not possible or useful here? | https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/richtlinien_forschungsdaten_bildungsforschung.pdf |
| project/legal_aspects/official_approval/statutatory_approval/conditions | What are the conditions for the permit? | https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/handreichung_fachkollegium_101_forschungsdaten.pdf |

2021-04-26 07:22 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>In the  &quot;Information for Building Language Corpora Under German Law&quot; of the DFG Review Board on Linguistics, https://www.dfg.de/download/pdf/foerderung/antragstellung/forschun
I suggest inserting the URL address as hyperlink

```suggestion
		<dc:comment>In the &lt;a href=&quot;https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/guidelines_review_board_linguistics_corpora.pdf&quot; target=&quot;_blank&quot;&gt;&quot;Information for Building Language Corpora Under German Law&quot; of the DFG Review Board on Linguistics&quot;&lt;/a&gt; it is explicitly pointed to single rights of the originator and the necessity to obtain these rights. For the question &quot;Which rights have been obtained or what is the status of the rights collection?&quot; this attribute has been added.</dc:comment>
```

The resulting HTML is 

```html
In the <a href="https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/guidelines_review_board_linguistics_corpora.pdf" target="_blank">"Information for Building Language Corpora Under German Law" of the DFG Review Board on Linguistics"</a> ...
```

2021-04-26 07:46 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>Added for the question, if similar research data are already available and why these cannot be used. The DFG Review Board 112 &quot;Economics&quot; and the German Federal Ministry of Ed
I suggest also putting the document title in italics, since it already contains quoted words

```suggestion
		<dc:comment>Added for the question, if similar research data are already available and why these cannot be used. The DFG Review Board 112 &quot;Economics&quot; and the German Federal Ministry of Education and Research (BMBF) published recommendations concerning this question, e.g. &lt;a href=&quot;https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/richtlinien_forschungsdaten_bildungsforschung.pdf&quot; target=&quot;_blank&quot;&gt;&lt;em&gt;Bereitstellung und Nutzung quantitativer Forschungsdaten in der Bildungsforschung: Memorandum des Fachkollegiums &quot;Erziehungswissenschaft&quot;&lt;/em&gt;&lt;/a&gt;
</dc:comment>
```

HTML Output:
```html
<a href="https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/richtlinien_forschungsdaten_bildungsforschung.pdf" target="_blank"><em>Bereitstellung und Nutzung quantitativer Forschungsdaten in der Bildungsforschung: Memorandum des Fachkollegiums "Erziehungswissenschaft"</em></a>
```

Instead of `<em>`, `<i>` can be used.

2021-04-26 07:55 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>Added for the question which data documention is only available on request. The question may be of relevance for DFG projects in educational research, see Petra Stanat, Bereitstellung u
```suggestion
		<dc:comment>Added for the question which data documention is only available on request. The question may be of relevance for DFG projects in educational research: see Petra Stanat, &lt;a href=&quot;https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/richtlinien_forschungsdaten_bildungsforschung.pdf&quot; target=&quot;_blank&quot;&gt;&lt;em&gt;Bereitstellung und Nutzung quantitativer Forschungsdaten in der Bildungsforschung: Memorandum des Fachkollegiums &quot;Erziehungswissenschaft&quot; der DFG&lt;/em&gt;&lt;/a&gt;</dc:comment>
```

2021-04-26 08:11 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>Added for the question &quot;What are the conditions for the permit?&quot;, recommended in the Manual on handling research data of the DFG review board &quot;Ancient Cultures&quot;, i.e
```suggestion
		<dc:comment>Added for the question &quot;What are the conditions for the permit?&quot;, recommended in the &lt;a href=&quot;https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/handreichung_fachkollegium_101_forschungsdaten.pdf&quot; target=&quot;_blank&quot;&gt;Manual on handling research data of the DFG review board &quot;Ancient Cultures&quot;, i.e. Fachkollegium &quot;Alte Kulturen&quot;, Handreichung zum Umgang mit Forschungsdaten&lt;/a&gt;</dc:comment>
```

2021-04-26 08:13 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>Added for the question which data documention is only available on request. The question may be of relevance for DFG projects in educational research, see Petra Stanat, Bereitstellung u
```suggestion
		<dc:comment>Added for the question which data documention is only available on request. The question may be of relevance for DFG projects in educational research, see Petra Stanat, &lt;a href=&quot;https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/richtlinien_forschungsdaten_bildungsforschung.pdf&quot; target=&quot;_blank&quot;&gt;&lt;em&gt;Bereitstellung und Nutzung quantitativer Forschungsdaten in der Bildungsforschung: Memorandum des Fachkollegiums &quot;Erziehungswissenschaft&quot; der DFG&lt;/em&gt;&lt;/a&gt;</dc:comment>
```

2021-04-26 08:14 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>Added for the question &quot;What are the conditions for the permit?&quot;, recommended in the Manual on handling research data of the DFG review board &quot;Ancient Cultures&quot;, i.e
```suggestion
		<dc:comment>Added for the question &quot;What are the conditions for the permit?&quot;, recommended in the &lt;a href=&quot;https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/handreichung_fachkollegium_101_forschungsdaten.pdf&quot; target=&quot;_blank&quot;&gt;Manual on handling research data of the DFG review board &quot;Ancient Cultures&quot;, i.e. Fachkollegium &quot;Alte Kulturen&quot;, Handreichung zum Umgang mit Forschungsdaten&lt;/a&gt;</dc:comment>
```

2021-04-26 08:17 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>Added for the question &quot;What are the conditions for the permit?&quot;, recommended in the Manual on handling research data of the DFG review board &quot;Ancient Cultures&quot;, i.e
Is it the same question as before?

```suggestion
		<dc:comment>Added for the question &quot;What are the conditions for the permit?&quot;, recommended in the &lt;a href=&quot;https://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/handreichung_fachkollegium_101_forschungsdaten.pdf&quot; target=&quot;_blank&quot;&gt;Manual on handling research data of the DFG review board &quot;Ancient Cultures&quot;, i.e. Fachkollegium &quot;Alte Kulturen&quot;, Handreichung zum Umgang mit Forschungsdaten&lt;/a&gt;</dc:comment>
```

2021-04-26 08:18 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>Added for the question &quot;What are the conditions for the permit?&quot;, recommended in the Manual on handling research data of the DFG review board &quot;Ancient Cultures&quot;, i.e
Many attributes were sorted but i assume they remained the same :)

2021-04-26 09:30 UTC, torsten-rathmann commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>In the  &quot;Information for Building Language Corpora Under German Law&quot; of the DFG Review Board on Linguistics, https://www.dfg.de/download/pdf/foerderung/antragstellung/forschun
In RDMO 1.5.5 sind die comment-Tags der Attribute reine Textfelder, d.h. eine Interpretation als HTML findet nicht statt, jedenfalls nicht im Firefox. Deshalb hatte ich alle HTML-Tags entfernt, um die Lesbarkeit zu verbessern. Mit dem Änderungswunsch kämen sie wieder hinein, aber wo werden die als klickbare Links angezeigt?

Das soll aber keine Grundsatzfrage sein und wenn die Änderung wirklich gewünscht wird, bin ich bereit, sie zu übernehmen.

2021-04-27 08:33 UTC, Zack-83 commented on rdmorganiser/domain/rdmo.xml
> +		<dc:comment>In the  &quot;Information for Building Language Corpora Under German Law&quot; of the DFG Review Board on Linguistics, https://www.dfg.de/download/pdf/foerderung/antragstellung/forschun
> In RDMO 1.5.5 sind die comment-Tags der Attribute reine Textfelder, d.h. eine Interpretation als HTML findet nicht statt
Ah, du hast Recht - die Visualisierung der _Attribute_ zeigt keine zusätzliche Informationen. (Schade!)
> Mit dem Änderungswunsch kämen sie wieder hinein, aber wo werden die als klickbare Links angezeigt?
Meine Absicht war, sie den Dokumenttiteln
> Das soll aber keine Grundsatzfrage sein und wenn die Änderung wirklich gewünscht wird, bin ich bereit, sie zu übernehmen.
Das wäre höchstens ein Änderungswunsch für die Dokumentationsseite https://rdmorganiser.github.io/terms/ . Für Ansichten wird auch der Hilfetext gezeigt (aber sie sind ja viel weniger als die Attributen oder die Fragen...)
![grafik](https://user-images.githubusercontent.com/37865804/116210868-8c189200-a743-11eb-8896-bcb2d77b441f.png)
Ich bestehe aber nicht darauf.
Die krumme Gänsefüsschen scheinen auch keine Problemen zu bereiten.
Daher kann ich gerne meinen Vorschlag zurücknehmen. :)

2021-05-17 14:28 UTC, jmfrenzel requested changes
This file is corrupt. It has multiple entries of the same attributes. Please compare to https://github.com/rdmorganiser/rdmo-catalog/blob/dev/rdmorganiser/domain/rdmo.xml 

 I recommend to make a fresh fork from dev branch and add your six new attributes.

2021-05-18 19:09 UTC, torsten-rathmann commented
Thank you for checking! I simply exported my domain. I will try it again with a fresh fork and an editor in a new pull request.

2021-05-18 19:09 UTC, closed without merging

2021-05-19 07:55 UTC, jmfrenzel commented
Closed in favor of https://github.com/rdmorganiser/rdmo-catalog/pull/47