Corrections VW_Science_Europe
rdmorganiser/rdmo-catalog pull request #52
Opened 2021-06-11 08:48 UTC by laura-tte

Correct typos and add further links
Changes from the LMU/eHumanities-Project

2021-07-20 08:12 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +If new data is collected or produced: &lt;/br&gt;
I don't agree: "data" is plural (even if nowadays the word is misused).
```suggestion
If new data are collected or produced: &lt;/br&gt; 
```

2021-07-20 08:22 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +* Who will hold the copyrights and controls the access. This is especially important in multi-partner projects with multiple owners, where the consortium agreement should cover these questions.
```suggestion
* Who will hold the copyrights and controls the access? This is especially important in multi-partner projects with multiple owners, where the consortium agreement should cover these questions.
```

2021-07-20 08:46 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +* What access conditions will apply? Will it be openly accessible? Will there be access restrictions imposed by the copyright holder? If so which restrictions and why?
```suggestion
* What access conditions will apply? Will the dataset be openly accessible? Will there be access restrictions imposed by the copyright holder? If so, which restrictions and why?
```

2021-07-20 08:46 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +		<text lang="en">Who will be the owner of the dataset? Meaning who will hold the rights to control access?</text>
```suggestion
		<text lang="en">Who will be the owner of the dataset, i.e. who will hold the rights to control access?</text>
```

2021-07-20 08:48 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +* Was werden die Zugriffsbedingungen sein? Werden die Daten frei zugänglich gemacht oder gibt es Zugriffsbeschränkungen durch den Urheber?  Falls dem so ist, begründen Sie dies.
```suggestion
* Was werden die Zugriffsbedingungen sein? Werden die Daten frei zugänglich gemacht oder gibt es Zugriffsbeschränkungen durch den Urheber? Im Fall von Beschränkungen, begründen Sie dies.
```

2021-07-20 08:51 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +Further you should discuss how the data can be found and which search tools will list the dataset. If you choose a publication via a repository this information is usually automatically indexed by co
```suggestion
Further you should discuss how the data can be found and which search tools will list the dataset. If you choose a publication via a repository this information is usually automatically indexed by common search engines. If you want or have to make the data available upon request, you could use a free repository such as &lt;a href=&quot;https://zenodo.org&quot; target=&quot;_blank&quot;&gt;Zenodo&lt;/a&gt; to publish only the meta-information (titel, authors, contact information, a short abstract).
```

2021-07-20 08:52 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +Weiter sollte diskutiert werden, wie die Daten aufgefunden werden können. Etwa durch eine Suche in Fachdatenbanken oder über Suchmaschinen. Bei Datenpublikationen über Repositorien geschieht dies mei
```suggestion
Weiter sollte diskutiert werden, wie die Daten aufgefunden werden können. Etwa durch eine Suche in Fachdatenbanken oder über Suchmaschinen. Bei Datenpublikationen über Repositorien geschieht dies meist automatisch, bei Daten, die nur auf Anfrage zugänglich sind, ist dies schwieriger zu leisten. Eine mögliche Lösung ist die Publikation der reinen Meta-Informationen zum Datensatz über ein Repositorium, wie &lt;a href=&quot;https://zenodo.org&quot; target=&quot;_blank&quot;&gt;Zenodo&lt;/a&gt; oder &lt;a href=&quot;https://www.radar-service.eu/de&quot; target=&quot;_blank&quot;&gt;RADAR&lt;/a&gt;, mit Kontaktinformationen für interessierte Forschende.
```

2021-07-20 08:54 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +For software consider licences like the &lt;a href=&quot;https://opensource.org/licenses/gpl-license&quot; target=&quot;_blank&quot;&gt;GNU public licence&lt;/a&gt; or the &lt;a href=&quot;https://op
```suggestion
For software you might consider licences like the &lt;a href=&quot;https://opensource.org/licenses/gpl-license&quot; target=&quot;_blank&quot;&gt;GNU public licence&lt;/a&gt; or the &lt;a href=&quot;https://opensource.org/licenses/MIT&quot; target=&quot;_blank&quot;&gt;MIT licence&lt;/a&gt;, which both allow for easy re-use.</help>
```

2021-07-20 08:55 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +		<help lang="en">If you use an established repository like &lt;a href=&quot;https://zenodo.org&quot; target=&quot;_blank&quot;&gt;Zenodo.org&lt;/a&gt;, &lt;a href=&quot;https://www.radar-service.eu/
```suggestion
		<help lang="en">If you use an established repository like &lt;a href=&quot;https://zenodo.org&quot; target=&quot;_blank&quot;&gt;Zenodo&lt;/a&gt;, &lt;a href=&quot;https://www.radar-service.eu/en&quot; target=&quot;_blank&quot;&gt;RADAR&lt;/a&gt;, &lt;a href=&quot;https://www.pangaea.de&quot; target=&quot;_blank&quot;&gt;Pangaea&lt;/a&gt; or &lt;a href=&quot;https://www.gesis.org/en/home&quot; target=&quot;_blank&quot;&gt;GESIS&lt;/a&gt;, the data will be stored securely and maintained beyond the lifetime of the grant.  Theses repositories usually follow established standards. If you use a non-standard repository, the local IT centre or even your own server, then you should address in detail how the data will be kept curated and intact after the funding has ended and how you will ensure that the data can be accessed and recovered in the long run.</help>
```

2021-07-20 08:55 UTC, Zack-83 commented on shared/ub_fau_erlangen_nuernberg/ScienceEurope_VW_Stiftung/catalog_VW_SE.xml
> +		<help lang="de">Wenn für die Aufbewahrung ein anerkanntes Repositorium wie &lt;a href=&quot;https://zenodo.org&quot; target=&quot;_blank&quot;&gt;Zenodo.org&lt;/a&gt;, &lt;a href=&quot;https://www.
```suggestion
		<help lang="de">Wenn für die Aufbewahrung ein anerkanntes Repositorium wie &lt;a href=&quot;https://zenodo.org&quot; target=&quot;_blank&quot;&gt;Zenodo&lt;/a&gt;, &lt;a href=&quot;https://www.radar-service.eu/de&quot; target=&quot;_blank&quot;&gt;RADAR&lt;/a&gt;, &lt;a href=&quot;https://www.gesis.org/home&quot; target=&quot;_blank&quot;&gt;GESIS&lt;/a&gt; oder &lt;a href=&quot;https://www.pangaea.de&quot; target=&quot;_blank&quot;&gt;Pangaea&lt;/a&gt; verwendet wird, dann genügt es darauf hinzuweisen, dass das Repositorium in der Community verbreitet ist und lange Erfahrung mit der Sicherung und ggf. Kuratierung von Forschungsdaten hat. Sollten Sie die Daten anderweitig, etwa an einem Rechenzentrum oder über einen eigenen Server sichern, dann sollte unbedingt erklärt werden, wie die Daten langfristig (insbesondere über das Ende der Förderung hinaus) gepflegt werden und ihre Sicherheit garantiert wird.</help>
```

2021-07-20 08:57 UTC, Zack-83 requested changes
Vielen Dank für die große Arbeit - ich habe ein paar minimale Korrekturvorschläge eingebaut

2021-07-20 09:00 UTC, Zack-83 commented
Noch eine Anmerkung: seit Kurzem führen wir die _Merge_ in den Zweig `dev` aus und aktualisieren den `master` nur bei größeren _Releases_. Das justieren wir später :)

2021-07-21 15:17 UTC, torsten-rathmann commented
Ich bin um eine Stellungnahme gebeten worden und möchte zunächst einmal wissen, ob der neue Fragenkatalog in den [share-Bereich unseres GitHub](https://github.com/rdmorganiser/rdmo-catalog/tree/master/shared) oder in den [Kernbereich](https://github.com/rdmorganiser/rdmo-catalog/tree/master/rdmorganiser/questions) aufgenommen werden soll. Die Aufnahme in den share-Bereich wäre lediglich mit einer technischen Funktionskontrolle verbunden und hätte den Vorteil, dass der neue Fragenkatalog schon bald über unser GitHub zur Verfügung stünde. Ein Fragenkatalog im Kernbereich hat natürlich eine hohe Sichtbarkeit. Die Aufnahme eines Fragenkatalogs, der von außen kommt, in den Kernbereich wäre aber ein ungewöhnlicher Vorgang. Ich würde das gern erst in der Content-Gruppe diskutieren.

2021-07-30 09:46 UTC, laura-tte commented
> 
> 
> Zur Info: seit Kurzem führen wir die _Merge_ in den Zweig `dev` aus und aktualisieren den `master` nur bei größeren _Releases_. Das justieren wir später :)

Vielen Dank für den Hinweis! Das werden wir in Zukunft beachten. 
Die vorgeschlagenen Änderungen im Katalog können gerne direkt so übernommen werden.

2021-08-02 16:39 UTC, Zack-83 approved these changes

2021-08-02 16:54 UTC, merged