Fix enumerations and line breaks
rdmorganiser/rdmo-catalog pull request #57
Opened 2021-07-09 07:59 UTC by ClaraRosalie

This PR fixes the formatting of enumerations and line breaks in [rdmo.xml](https://github.com/rdmorganiser/rdmo-catalog/blob/dev/rdmorganiser/questions/rdmo.xml) as described in #5. To identify the affected questions https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/pull/1/files was used as a template.

2021-07-09 08:26 UTC, jmfrenzel approved these changes
Looks ok. The enumeration and paragraphs are rendered in [rdmo v1.5.5]( https://github.com/rdmorganiser/rdmo/releases/tag/1.5.5)

2021-07-20 07:43 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +
```suggestion
```

2021-07-20 07:46 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +
The double newline _between_ bullets is not necessary. I don't know if it has side effects, such as separating the bullets into several lists...

2021-07-20 07:59 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> + Further discipline-specific guidelines on the handling of Research Data are provided by the &lt;a href=&quot;https://www.dfg.de/en/research_funding/proposal_review_decision/applicants/research_data/
To my memory, when a XML node has multiline content, the closing tag should be on a newline, otherwise some indenting scripts have difficulties to find it. I observed that on Notepad++ some three years ago, but apparently it is not a problem any more.

2021-07-20 08:05 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +In bestimmten Bereichen gelten spezifische Gesetze, die über den Landesdatenschutzgesetzen bzw. &lt;a href=&quot;http://www.gesetze-im-internet.de/bdsg_2018/&quot; target=&quot;_blank&quot;&gt;Bundes
From here on the enumerations were not fixed - either we add the newlines, or we decide they are not worth to be shown as a list 
```suggestion
In bestimmten Bereichen gelten spezifische Gesetze, die über den Landesdatenschutzgesetzen bzw. &lt;a href=&quot;http://www.gesetze-im-internet.de/bdsg_2018/&quot; target=&quot;_blank&quot;&gt;Bundesdatenschutzgesetz (BDSG)&lt;/a&gt; stehen.

* Für medizinischen Daten ist bspw. das Zehnte Sozialgesetzbuch (SGB X) anwendbar,

* Für Daten des Mikrozensus das Bundesstatistikgesetz (BStatG).

* Für Forschung in Schulen in NRW das Schulgesetz NRW (SchulG NRW)

 Demzufolge können je nach Forschungsprojekt auch mehrere Gesetze betroffen sein.</help>
```

2021-07-20 08:07 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +Wenn Sie diese Frage mit &quot;Ja&quot; beantworten, informieren Sie sich bei der/dem Datenschutzbeauftragten Ihrer Institution, welche zusätzlichen Schutzmaßnahmen notwendig sind. * &lt;a href=&quot
as above
```suggestion
Wenn Sie diese Frage mit &quot;Ja&quot; beantworten, informieren Sie sich bei der/dem Datenschutzbeauftragten Ihrer Institution, welche zusätzlichen Schutzmaßnahmen notwendig sind.

* &lt;a href=&quot;https://dsb.ruhr-uni-bochum.de/&quot; target=&quot;_blank&quot;&gt;Ruhr-Universität Bochum&lt;/a&gt;

* &lt;a href=&quot;https://www.uni-due.de/verwaltung/organisation/just_datenschutz.php&quot; target=&quot;_blank&quot;&gt;Universität Duisburg-Essen&lt;/a&gt;

 * &lt;a href=&quot;https://www.tu-dortmund.de/universitaet/organisation/beauftragte-vertrauenspersonen/#accordion-2213-764&quot; target=&quot;_blank&quot;&gt;Technische Unversität Dortmund&lt;/a&gt;</help>
```

2021-07-20 08:08 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +		<help lang="de">Grundsätzlich gilt, dass eine Erhebung, Verarbeitung, Archivierung und Veröffentlichung personenbezogener Daten nur zulässig ist, wenn eine entsprechende „informierte Einwilligung“
```suggestion
		<help lang="de">Grundsätzlich gilt, dass eine Erhebung, Verarbeitung, Archivierung und Veröffentlichung personenbezogener Daten nur zulässig ist, wenn eine entsprechende „informierte Einwilligung“ der Betroffenen vorliegt. Nur in ganz wenigen Ausnahmefällen wird diese nicht benötigt. Bitte informieren Sie sich ggf. bei der/dem Datenschutzbeauftragten Ihrer Institution über die notwendigen Bedingungen für die Einwilligung.

* &lt;a href=&quot;https://dsb.ruhr-uni-bochum.de/&quot; target=&quot;_blank&quot;&gt;Ruhr-Universität Bochum&lt;/a&gt; * &lt;a href=&quot;https://www.uni-due.de/verwaltung/organisation/just_datenschutz.php&quot; target=&quot;_blank&quot;&gt;Universität von Duisburg-Essen&lt;/a&gt;

* &lt;a href=&quot;https://www.tu-dortmund.de/universitaet/organisation/beauftragte-vertrauenspersonen/#accordion-2213-764&quot; target=&quot;_blank&quot;&gt;Technische Unversität Dortmund&lt;/a&gt;</help>
```

2021-07-20 08:10 UTC, Zack-83 requested changes
Well done and many thanks for that. I have requested some minor changes

2021-07-20 13:00 UTC, torsten-rathmann commented on rdmorganiser/questions/rdmo.xml
> +(If the dataset is archived at several places, you may answer this question with yes, if this applies to at least one of these.)</text>
Paragraphs in help texts are a good idea but the questions itself shouldn't be divided up.

2021-07-20 13:22 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +(If the dataset is archived at several places, you may answer this question with yes, if this applies to at least one of these.)</text>
Is there a reason why not? This PR intends to reintegrate the original layout of rdmo-catalog questions and help text  that was lost via https://github.com/rdmorganiser/rdmo-catalog/commit/092acbf3ac4fdc6adf97735d48bfc64a4c380c62

2021-07-20 13:36 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> +
This PR intends to reintegrate the original layout of rdmo-catalog questions and help text  that was lost via https://github.com/rdmorganiser/rdmo-catalog/commit/092acbf3ac4fdc6adf97735d48bfc64a4c380c62
The current version is rendered as intended when importing it into the latest rdmo 1.5.5. 
For the sake of a clean reintegration the old layout, I suggest a separate PR that implements further optimizations.

2021-07-20 13:41 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
> + Further discipline-specific guidelines on the handling of Research Data are provided by the &lt;a href=&quot;https://www.dfg.de/en/research_funding/proposal_review_decision/applicants/research_data/
If that is not a problem any more and given the testing of this PR i.e. importing the catalog and manually checking the rendered questions in the UI, did not show any errors are there any objections approving this PR?

2021-07-20 17:04 UTC, torsten-rathmann commented on rdmorganiser/questions/rdmo.xml
> +(If the dataset is archived at several places, you may answer this question with yes, if this applies to at least one of these.)</text>
Questions look like headings and shouldn't be longer than necessary in my opinion. And the now separated text _If the dataset is archived at several places, you may answer this question with yes, if this applies to at least one of these_ is not only part of the question but repeated in the help text too. I recommend to delete it in the question. Or is there a special reasion to have it twice?

2021-07-20 17:07 UTC, torsten-rathmann approved these changes

2021-07-21 06:33 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +* &lt;a href=&quot;https://dsb.ruhr-uni-bochum.de/&quot; target=&quot;_blank&quot;&gt;Ruhr-Universität Bochum&lt;/a&gt; * &lt;a href=&quot;https://www.uni-due.de/verwaltung/organisation/just_datensch
```suggestion
* &lt;a href=&quot;https://dsb.ruhr-uni-bochum.de/&quot; target=&quot;_blank&quot;&gt;Ruhr-Universität Bochum&lt;/a&gt;

 * &lt;a href=&quot;https://www.uni-due.de/verwaltung/organisation/just_datenschutz.php&quot; target=&quot;_blank&quot;&gt;Universität von Duisburg-Essen&lt;/a&gt;
```

2021-07-21 07:04 UTC, Zack-83 commented on rdmorganiser/questions/rdmo.xml
> +
@jmfrenzel I was wondering why the newline should be _double_ : within a list, Markdown only requires one. Anyway, fine with me.

2021-07-21 07:08 UTC, Zack-83 approved these changes

2021-07-21 07:09 UTC, merged