add software version in help text
rdmorganiser/rdmo-catalog pull request #82
Opened 2021-09-15 12:23 UTC by ClaraRosalie

refs #80 

note: french and italian translation is missing and needs to be added

2021-09-16 15:09 UTC, jmfrenzel requested changes

2021-09-16 15:09 UTC, jmfrenzel commented on rdmorganiser/questions/rdmo.xml
>  		<verbose_name_plural lang="en"/>
Might want to add the your change also to the English helptext

2021-09-27 19:18 UTC, jmfrenzel approved these changes

2021-10-04 06:56 UTC, Zack-83 approved these changes

2021-10-04 06:56 UTC, merged